### ISSUE TITLE
EXIF-based rotation fails on 180

### ISSUE THREAD

**Issue by dirkf** [henrythasler/simple-image-reducer#8]
Using the version installed from `simple-image-reducer_1.0.2+git20191008-1_all.deb`, if an image being processed has EXIF Orientation specifying a 180 degree rotation and the option to rotate "According to EXIF data" is set, the operation fails with this console error:
```
Traceback (most recent call last):
  File "/usr/bin/simple-image-reducer", line 494, in execute_iter
    self.task.next()
  File "/usr/bin/Desktop/simple-image-reducer", line 449, in execute_task
    for method in transpose_methods:
TypeError: 'int' object is not iterable

```
There seems to be a typo in the definition of the `exif_to_transpose` sequence, and this is still in the latest version (line 408).

This patch fixes the typo. It also removes a duplicate import and adds a catch-all exception handler to `execute_iter()` which allows some sort of recovery in the UI (eg, press the 'minus' button) to try the same file with different settings if an otherwise untrapped error occurs when processing an image.

```
--- old/simple-image-reducer	2019-10-11 09:30:50.000000000 +0100
+++ new/simple-image-reducer	2020-03-23 20:09:18.772118707 +0000
@@ -23,7 +23,6 @@
 import os
 import os.path
 import urllib.request, urllib.parse, urllib.error
-import urllib.parse
 import configparser
 
 from PIL import Image
@@ -405,7 +404,7 @@
         exif_to_transpose = [
                 (),
                 (Image.FLIP_LEFT_RIGHT,),
-                (Image.ROTATE_180),
+                (Image.ROTATE_180,),
                 (Image.FLIP_TOP_BOTTOM,),
                 (Image.ROTATE_90, Image.FLIP_LEFT_RIGHT),
                 (Image.ROTATE_270,),
@@ -496,6 +495,9 @@
             self.task = None
             self.destroy()
             return False
+        except:
+            self.task = None
+
         return True
 
     def execute(self, *args):
```

**Comment by henrythasler** [comment]
Thanks. Could you create a PR so I can easily apply this fix?
